### ISSUE TITLE
Symphony 2.6 bootstrapping

### ISSUE THREAD

**Issue by HostTech** [symphonists/rest_api#14]
Great extension!

I did a fresh build today and came up against the following issue.

The handler will not work (in 2.6+) without adding the autoload script first, would be great if you could could create some kind of conditional DOCROOT checker so this extension continues to work on future symphony releases.
```
require_once(DOCROOT . '/vendor/autoload.php');
```

**Comment by nitriques** [comment]
Would you mind sending a PR ?

**Comment by nitriques** [comment]
[Fixed and released in 1.4.0](https://github.com/symphonists/rest_api/releases/tag/1.4.0)
