### ISSUE TITLE
REST API for 2.6.4

### ISSUE THREAD

**Issue by sonamgupta28** [symphonists/rest_api#16]
I am trying using the rest API which is installed in version 2.6.4 but I am unable to access it.

Is the API supported with symphony 2.6.4?

While consuming the API with firefox RESTClient I am getting below error:
    <br />
    <b>Fatal error</b>:  Class 'Symphony' not found in <b>C:\xampp\htdocs\symphony\symphony\lib\boot\bundle.php</b> on line <b>17</b><br />

Please provide support

Regards
Sonam

**Comment by sonamgupta28** [comment]
It is working fine as per PR #14

**Comment by nitriques** [comment]
[Fixed and released in 1.4.0](https://github.com/symphonists/rest_api/releases/tag/1.4.0) Thanks!
